#!/usr/bin/env python3
import json
import os
import sys
import urllib.error
import urllib.request

SYSTEM_PROMPT = """You are the OpenBeagle branch review assistant.

You review a new branch commit or commit series and prepare a merge request note for the human maintainer.
Your job is to request useful human input, identify risks, and suggest concrete next steps.
Do not claim tests passed or failed unless the context says so.
Do not request external cloud access.
Do not include secrets.
Be concise and practical.
"""

USER_TEMPLATE = """Review this branch context and produce a merge request description/comment.

The purpose of this MR is to request additional human input on a new commit or branch.

Required format:

<!-- openbeagle-webide-agent:agent-review -->

## OpenBeagle agent review

**Summary:** <one sentence>

**What changed:**
- <brief bullets>

**Questions for the maintainer:**
- <questions that need human input, if any>

**Risks or things to verify:**
- <brief bullets>

**Suggested next steps:**
- <brief bullets>

**Model note:** Generated by local Ollama on ollama.openbeagle.org.

Context JSON follows:

{context}
"""


def call_ollama(base_url: str, model: str, prompt: str) -> str:
    url = base_url.rstrip("/") + "/api/chat"
    payload = {
        "model": model,
        "messages": [
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": prompt},
        ],
        "stream": False,
        "keep_alive": -1,
        "options": {
            "temperature": 0.2
        },
    }

    req = urllib.request.Request(
        url,
        data=json.dumps(payload).encode("utf-8"),
        headers={"Content-Type": "application/json"},
        method="POST",
    )

    try:
        with urllib.request.urlopen(req, timeout=600) as resp:
            data = json.loads(resp.read().decode("utf-8"))
    except urllib.error.HTTPError as e:
        body = e.read().decode("utf-8", errors="replace")
        raise SystemExit(f"Ollama HTTP error {e.code}: {body}") from e

    return data["message"]["content"]


def main() -> int:
    if len(sys.argv) != 2:
        print(f"Usage: {sys.argv[0]} <commit_context.json>", file=sys.stderr)
        return 2

    base_url = os.environ.get("OPENBEAGLE_OLLAMA_BASE_URL", "http://127.0.0.1:11434")
    model = os.environ.get("OPENBEAGLE_OLLAMA_MODEL", "qwen3-coder:30b")

    with open(sys.argv[1], "r", encoding="utf-8") as f:
        context_obj = json.load(f)

    context = json.dumps(context_obj, indent=2)[:30000]
    prompt = USER_TEMPLATE.format(context=context)
    print(call_ollama(base_url, model, prompt))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())